### ISSUE TITLE
bug(@vtmn/react): VtmnDropdownItem Invalid hook call

### ISSUE THREAD

**Issue by romuleald** [Decathlon/vitamin-web#1328]
I'm facing a weird `Invalid hook call` with vtmn react with a very simple usage

Imported this way
```
import { VtmnDropdown, VtmnDropdownItem } from '@vtmn/react';
```
The code that throw
```tsx
return (
    <div className="more-options-button">
      <Button />
      <VtmnDropdown>
        <VtmnDropdownItem id="dropdown-0-opt-1" name="dropdown-0" value="item 1">
          Dropdown Item 1
        </VtmnDropdownItem>
        <VtmnDropdownItem id="dropdown-0-opt-2" name="dropdown-0" value="item 2" icon="user-line">
          Dropdown Item 2
        </VtmnDropdownItem>
        <VtmnDropdownItem id="dropdown-0-opt-3" name="dropdown-0" value="item 3" divider>
          Dropdown Item 3
        </VtmnDropdownItem>
        <VtmnDropdownItem id="dropdown-0-opt-4" name="dropdown-0" value="item 4">
          Dropdown Item 4
        </VtmnDropdownItem>
      </VtmnDropdown>
    </div>
  );

```
The stack trace says
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
printWarning @ react.development.js:209
react.development.js:1622 Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at Object.useState (react.development.js:1622:1)
    at VtmnDropdownItem (VtmnDropdownItem.tsx:42:41)
```

![image](https://user-images.githubusercontent.com/144375/212081520-cbf07072-31aa-4157-b1ef-2b63d01850ca.png)

**Version affected**
```
    "@vtmn/react": "^0.57.0",
```

**Comment by thibault-mahe** [comment]
Hi @romuleald, thanks for opening this issue !

Unfortunately I can't replicate your issue in my test envs : 

- local install with CRA & Typescript with both `@vtmn/react` `^0.57.0` and `^0.58.1` (`react ^18.2.0`)
- remote sandbox install with react-scripts: [https://codesandbox.io/s/vtmn-react-forked-npgqgv](https://codesandbox.io/s/vtmn-react-forked-npgqgv) (`react ^18.0.0`)

Could you give me more informations about your env (framework, react version, build tool, etc.) or maybe share a sandbox so I can help you please ?

Thanks!

**Comment by romuleald** [comment]
My bad, a bad config happened while installing it from local path, seems to be a react/npm bug
